---
- hosts: local
  roles:
  - setup
  - zsh
  - dev
  - node
  - java
  - maven
  - docker
  - vscode
  - intellij
  - spotify
  - { role: linux_tweaks, when: ansible_os_family == 'Debian' }
  - chrome

  
