

- name: Add Microsoft repo key
  apt_key:
    keyserver: "{{ key_server }}"
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
  become: yes

- name: Add Microsoft repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    update_cache: yes
    state: present
  become: yes

- name: Install VSCode
  apt:
    name: code
    force_apt_get: yes
  become: yes
