- name: Set up apt to use repos over https
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes

- name: Add Microsoft repo key
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Install VSCode
  apt:
    name: code
  become: yes