---

- name: Download Maven
  unarchive: 
    src: http://www.mirrorservice.org/sites/ftp.apache.org/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
    dest: /opt/
    remote_src: yes
  become: yes

- name: Add MAVEN_HOME to zshrc
  lineinfile: 
    path: ~/.zshrc
    line: export MAVEN_HOME=/opt/apache-maven-3.6.1/bin

- name: Add MAVEN_HOME to PATH
  lineinfile: 
     path: ~/.zshrc
     line: export PATH=$MAVEN_HOME:$PATH
