---

- name: Download Maven
  unarchive: 
    src: "{{ maven.url }}"
    dest: /opt/
    remote_src: yes
  become: yes

- name: Add MAVEN_HOME to zshrc
  lineinfile: 
    path: "{{ zshrc.path }}"
    line: export MAVEN_HOME={{ maven.dir }}

- name: Add MAVEN_HOME to PATH
  lineinfile: 
     path: "{{ zshrc.path }}"
     line: export PATH=$MAVEN_HOME:$PATH
