- name: Add Spotify repo key
  shell: curl -sS https://download.spotify.com/debian/pubkey.gpg | sudo apt-key add - 
  become: yes

- name: Add Spotify repo
  shell: echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
  become: yes

- name: Install Spotify
  apt:
    name: spotify-client
    force_apt_get: yes
    update_cache: yes
  become: yes
    
