- name: Download Google Chrome .deb
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/chrome.deb

- name: Install Google Chrome
  apt:
    deb: /tmp/chrome.deb
    state: present
  become: yes
