- name: add to input group
  command: gpasswd -a $USER input
  become: yes

- name: Install setup packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - snapd
    - git
    - libinput-tools
    - ruby
    - xdotool
    - python3-pip
  become: yes

- name: Install Fusuma
  gem:
    name: fusuma
    state: latest
  become: yes
